### ISSUE TITLE
Getting random_cookie_name error

### ISSUE THREAD

**Issue by hunaidkhan2000** [mkhorasani/Streamlit-Authenticator#134] opened 2024-02-21 06:12 UTC
Hi @mkhorasani  thanks for this amazing package, I kindly request your assistance with an issue that's surfaced with a Streamlit app we've recently deployed on Azure cloud. From yesterday, we've been encountering a peculiar 'Random_cookie_name' error that's preventing some users from logging out. It's interesting to note that it's not a universal issue - some of our users from different geographical locations are able to logout without trouble. To assist you in troubleshooting, I'm attaching a screenshot along with a sample yml file and script. Your expertise and guidance on this matter would be greatly appreciated.
![image](https://github.com/mkhorasani/Streamlit-Authenticator/assets/34857371/6dff119b-2056-4d21-aa2c-c6e982de2984) 
yml file 
````
credentials:
  usernames:
    hk:
      email: hk@gmail.com
      name: hkhan
      password: "my hashed password" # 
##some other user names 
#file ends with 
cookie:
  expiry_days: 0
  key: "random_signature_key" # Must be a string
  name: "random_cookie_name" #we did not change it , kept it as random_cookie_name 
preauthorized:
  emails:
  - hk@gmail.com
```


our main file authentication code is 
```
with open('chatbot_users.yml') as file:  ##../
    config = yaml.load(file, Loader=SafeLoader)

authenticator = stauth.Authenticate(
    config['credentials'],
    config['cookie']['name'],
    config['cookie']['key'],
    config['cookie']['expiry_days'],
    config['preauthorized']
)
```

**Comment by mkhorasani** [comment] 2024-02-21 06:59
Hi @hunaidkhan2000, thank you for reaching out. Can you check to see if the associated reauthentication cookie is available on the browser when this exception is thrown? You can do this by hitting F12 and typing `document.cookie` in the console of your browser.

**Comment by hunaidkhan2000** [comment] 2024-02-21 09:06
Hi @mkhorasani  , I am not able to find document.cookie in my browser console.

**Comment by mkhorasani** [comment] 2024-02-21 12:12
Is this how you're trying to access your cookies? 
![image](https://github.com/mkhorasani/Streamlit-Authenticator/assets/38884731/b9dfc616-5626-4062-9ed1-a92376d8bc73)

**Comment by hunaidkhan2000** [comment] 2024-02-21 14:04
@mkhorasani  we tried this method also and this one also , Attaching the screenshot . Any idea?


![image](https://github.com/mkhorasani/Streamlit-Authenticator/assets/34857371/6d44373d-7596-457d-a637-45b670bfad0f)

**Comment by hunaidkhan2000** [comment] 2024-02-22 04:51
What steps should I take in the meantime? It appears that the issue is intermittent as some users can log out without problems, while others encounter a cookie error that prevents them from logging out every time. There is a possibility that users who are able to log out might have to deal with this issue @mkhorasani

**Comment by mkhorasani** [comment] 2024-02-22 06:07
You can try to place the logout() function within a try and except block. The new release should be made very soon.

**Comment by angelocamacho** [comment] 2024-02-22 06:30
I have this issue consistently when hosting on Streamlit cloud, but it works fine when hosting locally. I'm not seeing the cookie getting written when hosting on Streamlit cloud for me. Same issue across browsers as well. Tried Chrome and Firefox.

**Comment by mkhorasani** [comment] 2024-02-22 10:20
> I have this issue consistently when hosting on Streamlit cloud, but it works fine when hosting locally. I'm not seeing the cookie getting written when hosting on Streamlit cloud for me. Same issue across browsers as well. Tried Chrome and Firefox.

Which version of Streamlit-Authenticator are you using?

**Comment by angelocamacho** [comment] 2024-02-22 11:21
Collecting streamlit-authenticator

  Downloading streamlit_authenticator-0.3.1-py3-none-any.whl (17 kB)

**Comment by mkhorasani** [comment] 2024-02-22 11:45
I'm going to release v0.3.2 in the coming days, with the new version of Extra-Streamlit-Components v0.1.70 (the library that manages the cookies), hopefully these problems should be resolved.

**Comment by hunaidkhan2000** [comment] 2024-02-23 12:35
@mkhorasani  do let us know when you release the next version, that will help us

**Comment by elmighetto** [comment] 2024-02-27 00:18
Having the same issue. Solution I'm using: 
```
class FixedAuthenticate(stauth.Authenticate): 
  def _implement_logout(self):
        # Clears cookie and session state variables associated with the logged in user.
        try:
            self.cookie_manager.delete(self.cookie_name)
        except Exception as e: 
            print(e)
        self.credentials['usernames'][st.session_state['username']]['logged_in'] = False
        st.session_state['logout'] = True
        st.session_state['name'] = None
        st.session_state['username'] = None
        st.session_state['authentication_status'] = None

authenticator = FixedAuthenticate(...) 
```

It's a temporary fix that doesn't address the underlying issue of the cookie getting lost in the first place, but it does let the login complete even if the issue occurs. 

Explanation: inherit the Authenticate class, change the loggout implementation to catch exception from deleting the cookie.

**Comment by hunaidkhan2000** [comment] 2024-02-29 07:35
> Having the same issue. Solution I'm using:
> 
> ```
> class FixedAuthenticate(stauth.Authenticate): 
>   def _implement_logout(self):
>         # Clears cookie and session state variables associated with the logged in user.
>         try:
>             self.cookie_manager.delete(self.cookie_name)
>         except Exception as e: 
>             print(e)
>         self.credentials['usernames'][st.session_state['username']]['logged_in'] = False
>         st.session_state['logout'] = True
>         st.session_state['name'] = None
>         st.session_state['username'] = None
>         st.session_state['authentication_status'] = None
> 
> authenticator = FixedAuthenticate(...) 
> ```
> 
> It's a temporary fix that doesn't address the underlying issue of the cookie getting lost in the first place, but it does let the logout complete even if the issue occurs.
> 
> Explanation: inherit the Authenticate class, change the loggout implementation to catch exception from deleting the cookie.

Thank you so much, this worked and resolved my issue

**Comment by yhavin** [comment] 2024-03-06 21:47
> Having the same issue. Solution I'm using:
> 
> ```
> class FixedAuthenticate(stauth.Authenticate): 
>   def _implement_logout(self):
>         # Clears cookie and session state variables associated with the logged in user.
>         try:
>             self.cookie_manager.delete(self.cookie_name)
>         except Exception as e: 
>             print(e)
>         self.credentials['usernames'][st.session_state['username']]['logged_in'] = False
>         st.session_state['logout'] = True
>         st.session_state['name'] = None
>         st.session_state['username'] = None
>         st.session_state['authentication_status'] = None
> 
> authenticator = FixedAuthenticate(...) 
> ```
> 
> It's a temporary fix that doesn't address the underlying issue of the cookie getting lost in the first place, but it does let the logout complete even if the issue occurs.
> 
> Explanation: inherit the Authenticate class, change the loggout implementation to catch exception from deleting the cookie.

This works well for avoiding the fatal error, but it looks like authentication status isn't maintained because the cookie isn't found. So I have to log in every time I open the app. Is that a logical consequence of this cookie bug or am I making a different mistake?

**Comment by elmighetto** [comment] 2024-03-06 22:30
> This works well for avoiding the fatal error, but it looks like authentication status isn't maintained because the cookie isn't found. So I have to log in every time I open the app. Is that a logical consequence of this cookie bug or am I making a different mistake?

Yeah if the cookie is failing to get stored, then it wouldn't be able to keep you logged in. I wonder if this issue has to do with what browser you're using? I haven't tested with anything other than google chrome personally.

**Comment by yhavin** [comment] 2024-03-06 23:22
> > This works well for avoiding the fatal error, but it looks like authentication status isn't maintained because the cookie isn't found. So I have to log in every time I open the app. Is that a logical consequence of this cookie bug or am I making a different mistake?
> 
> Yeah if the cookie is failing to get stored, then it wouldn't be able to keep you logged in. I wonder if this issue has to do with what browser you're using? I haven't tested with anything other than google chrome personally.

When I set expiry days to a number, then the cookie stored. I had it at 0 before, because I wanted indefinite maintain of login, but it didn't store.

**Comment by xixiaoguai727** [comment] 2024-03-11 13:30
😭Hi @mkhorasani , may I ask when will the new version will be released?

**Comment by mkhorasani** [comment] 2024-03-11 15:34
> 😭Hi @mkhorasani , may I ask when will the new version will be released?

Apologies for the delay, still working on it.

**Comment by xixiaoguai727** [comment] 2024-03-13 05:38
> > 😭Hi @mkhorasani , may I ask when will the new version will be released?
> 
> Apologies for the delay, still working on it.

No need to apologies, you did a great work for us❤️! Just take your time!

**Comment by jalkestrup** [comment] 2024-03-15 11:50
Thanks for the post, I am facing a similar bug when using the logout, cookie key error. I can reproduce the error if I log in, then log out, and then log in, and try to log out again. I will go with the try fix for now, thanks.

**Comment by titoausten** [comment] 2024-03-22 14:56
> Having the same issue. Solution I'm using:
> 
> ```
> class FixedAuthenticate(stauth.Authenticate): 
>   def _implement_logout(self):
>         # Clears cookie and session state variables associated with the logged in user.
>         try:
>             self.cookie_manager.delete(self.cookie_name)
>         except Exception as e: 
>             print(e)
>         self.credentials['usernames'][st.session_state['username']]['logged_in'] = False
>         st.session_state['logout'] = True
>         st.session_state['name'] = None
>         st.session_state['username'] = None
>         st.session_state['authentication_status'] = None
> 
> authenticator = FixedAuthenticate(...) 
> ```
> 
> It's a temporary fix that doesn't address the underlying issue of the cookie getting lost in the first place, but it does let the logout complete even if the issue occurs.
> 
> Explanation: inherit the Authenticate class, change the loggout implementation to catch exception from deleting the cookie.

Beautiful!, this solved the bug. Thanks

**Closed** 2024-03-26 19:51 UTC
Labels: help wanted
